### ISSUE TITLE
Error on enable

### ISSUE THREAD

**Issue by Mataisplays** [nulli0n/NexEngine-spigot#13]
`[22:50:56 ERROR]: Error occurred while enabling NexEngine v2.2.4 build-29/08/2022 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at su.nexmedia.engine.NexEngine.setupNMS(NexEngine.java:79) ~[?:?]
        at su.nexmedia.engine.NexEngine.loadCore(NexEngine.java:56) ~[?:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:65) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant su.nexmedia.engine.Version.V1_16_R3
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at su.nexmedia.engine.Version.valueOf(Version.java:6) ~[?:?]
        at su.nexmedia.engine.Version.<clinit>(Version.java:19) ~[?:?]
        ... 12 more`

**Comment by nulli0n** [comment]
1.16 is not supported anymore.
