### ISSUE TITLE
Does it support 1.19.3?

### ISSUE THREAD

**Issue by Decypt** [nulli0n/NexEngine-spigot#18]
Hello, currently I am trying to set up a server with friends and when installing your plugin I keep running into a null exception issue. Is it because the plugin doesn't support 1.19.3 or is there another issue? I am running the 11/29/2022 version of the plugin. Thank you for your time! 

[06:23:46] [Server thread/ERROR]: Error occurred while enabling NexEngine v2.2.7 build-29/11/2022 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at su.nexmedia.engine.NexEngine.setupNMS(NexEngine.java:78) ~[?:?]
        at su.nexmedia.engine.NexEngine.loadCore(NexEngine.java:55) ~[?:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:69) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:220) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3612-Spigot-61bffe0-e85280e]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant su.nexmedia.engine.Version.V1_19_R2
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at su.nexmedia.engine.Version.valueOf(Version.java:6) ~[?:?]
        at su.nexmedia.engine.Version.<clinit>(Version.java:19) ~[?:?]

**Comment by nulli0n** [comment]
Yeah, not supported yet. Will release an update sometime soon.

**Comment by nulli0n** [comment]
Done, check Releases.
