### ISSUE TITLE
Error on MythicMobs hook.

### ISSUE THREAD

**Issue by jurian112211** [nulli0n/NexEngine-spigot#19]
Hello there, I'm getting this error:
```
[12:05:14 ERROR]: [NexEngine] Could not initialize hook for 'MythicMobsHK' !
[12:05:14 WARN]: java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/api/exceptions/InvalidMobTypeException
[12:05:14 WARN]:        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
[12:05:14 WARN]:        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
[12:05:14 WARN]:        at java.base/java.lang.Class.getConstructor0(Class.java:3578)
[12:05:14 WARN]:        at java.base/java.lang.Class.getConstructor(Class.java:2271)
[12:05:14 WARN]:        at NexEngine.jar//su.nexmedia.engine.hooks.HookManager.register(HookManager.java:46)
[12:05:14 WARN]:        at NexEngine.jar//su.nexmedia.engine.NexPlugin.registerHook(NexPlugin.java:128)
[12:05:14 WARN]:        at NexEngine.jar//su.nexmedia.engine.NexEngine.onHookLate(NexEngine.java:194)
[12:05:14 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor18.execute(Unknown Source)
[12:05:14 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[12:05:14 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:05:14 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:05:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[12:05:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:381)
[12:05:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[12:05:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[12:05:14 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[12:05:14 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[12:05:14 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[12:05:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[12:05:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[12:05:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:05:14 WARN]: Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.api.exceptions.InvalidMobTypeException
[12:05:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[12:05:14 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[12:05:14 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[12:05:14 WARN]:        ... 21 more
```

**Comment by nulli0n** [comment]
Update both plugins.

**Comment by jurian112211** [comment]
Nevermind, I was wrong.
Thanks for your support and the amazing pl😀
