### ISSUE TITLE
Could not pass event EntitySpawnEvent to NexEngine

### ISSUE THREAD

**Issue by WongIong** [nulli0n/NexEngine-spigot#2]
[05:46:13 ERROR]: Could not pass event EntitySpawnEvent to NexEngine v2.1.2 build-18/05/2022
java.lang.NullPointerException: Cannot invoke "su.nexmedia.engine.manager.player.blocktracker.TrackedChunk.isTracked(org.bukkit.block.Block)" because the return value of "su.nexmedia.engine.manager.player.blocktracker.TrackedWorld.getChunkOf(org.bukkit.block.Block)" is null
        at su.nexmedia.engine.manager.player.blocktracker.TrackedWorld.isTracked(TrackedWorld.java:19) ~[?:?]
        at su.nexmedia.engine.manager.player.blocktracker.PlayerBlockTracker.isTracked(PlayerBlockTracker.java:86) ~[?:?]
        at su.nexmedia.engine.manager.player.blocktracker.TrackListener.onEntityFallingSpawn(TrackListener.java:132) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor540.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntitySpawnEvent(CraftEventFactory.java:710) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:685) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1302) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1203) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnFallingBlock(CraftWorld.java:1642) ~[patched_1.16.5.jar:git-Paper-794]
        at me.olipulse.meteoritespro.Meteorites.MeteoriteCore.spawnMeteoriteCore(MeteoriteCore.java:35) ~[?:?]
        at me.olipulse.meteoritespro.Meteorites.Meteorite.spawnMeteorite(Meteorite.java:89) ~[?:?]
        at me.olipulse.meteoritespro.Meteorites.RandomMeteoriteHandler$1.run(RandomMeteoriteHandler.java:112) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by nulli0n** [comment]
Fixed.
