### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by Popsigurna** [nulli0n/NexEngine-spigot#23]
Failed to load - using purpur 1913 - crashes when it's the only plugin

[16:33:51 INFO]: [NexEngine] Enabling NexEngine v2.2.6 build-04/10/2022
[16:33:51 WARN]: java.lang.IllegalArgumentException: No enum constant su.nexmedia.engine.Version.V1_19_R2
[16:33:51 WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:274)
[16:33:51 WARN]:        at NexEngine.jar//su.nexmedia.engine.Version.valueOf(Version.java:6)
[16:33:51 WARN]:        at NexEngine.jar//su.nexmedia.engine.Version.<clinit>(Version.java:19)
[16:33:51 WARN]:        at NexEngine.jar//su.nexmedia.engine.NexEngine.setupNMS(NexEngine.java:79)
[16:33:51 WARN]:        at NexEngine.jar//su.nexmedia.engine.NexEngine.loadCore(NexEngine.java:56)
[16:33:51 WARN]:        at NexEngine.jar//su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:69)
[16:33:51 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:33:51 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372)
[16:33:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550)
[16:33:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:630)
[16:33:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:544)
[16:33:51 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
[16:33:51 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
[16:33:51 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[16:33:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[16:33:51 ERROR]: Error occurred while enabling NexEngine v2.2.6 build-04/10/2022 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at su.nexmedia.engine.NexEngine.setupNMS(NexEngine.java:79) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexEngine.loadCore(NexEngine.java:56) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:69) ~[NexEngine.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:630) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:544) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant su.nexmedia.engine.Version.V1_19_R2
        at java.lang.Enum.valueOf(Enum.java:274) ~[?:?]
        at su.nexmedia.engine.Version.valueOf(Version.java:6) ~[NexEngine.jar:?]
        at su.nexmedia.engine.Version.<clinit>(Version.java:19) ~[NexEngine.jar:?]
        ... 12 more
[16:33:51 INFO]: [NexEngine] Disabling NexEngine v2.2.6 build-04/10/2022
[16:33:51 ERROR]: Error occurred while disabling NexEngine v2.2.6 build-04/10/2022 (Is it up to date?)Failed to load - using purpur 1913 - crashes when it's the only plugin

[16:33:51 INFO]: [NexEngine] Enabling NexEngine v2.2.6 build-04/10/2022
[16:33:51 WARN]: java.lang.IllegalArgumentException: No enum constant su.nexmedia.engine.Version.V1_19_R2
[16:33:51 WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:274)
[16:33:51 WARN]:        at NexEngine.jar//su.nexmedia.engine.Version.valueOf(Version.java:6)
[16:33:51 WARN]:        at NexEngine.jar//su.nexmedia.engine.Version.<clinit>(Version.java:19)
[16:33:51 WARN]:        at NexEngine.jar//su.nexmedia.engine.NexEngine.setupNMS(NexEngine.java:79)
[16:33:51 WARN]:        at NexEngine.jar//su.nexmedia.engine.NexEngine.loadCore(NexEngine.java:56)
[16:33:51 WARN]:        at NexEngine.jar//su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:69)
[16:33:51 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[16:33:51 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372)
[16:33:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550)
[16:33:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:630)
[16:33:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:544)
[16:33:51 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
[16:33:51 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
[16:33:51 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[16:33:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[16:33:51 ERROR]: Error occurred while enabling NexEngine v2.2.6 build-04/10/2022 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at su.nexmedia.engine.NexEngine.setupNMS(NexEngine.java:79) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexEngine.loadCore(NexEngine.java:56) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:69) ~[NexEngine.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:630) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:544) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1913]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant su.nexmedia.engine.Version.V1_19_R2
        at java.lang.Enum.valueOf(Enum.java:274) ~[?:?]
        at su.nexmedia.engine.Version.valueOf(Version.java:6) ~[NexEngine.jar:?]
        at su.nexmedia.engine.Version.<clinit>(Version.java:19) ~[NexEngine.jar:?]
        ... 12 more
[16:33:51 INFO]: [NexEngine] Disabling NexEngine v2.2.6 build-04/10/2022
[16:33:51 ERROR]: Error occurred while disabling NexEngine v2.2.6 build-04/10/2022 (Is it up to date?)

**Comment by nulli0n** [comment]
Use the latest engine version.
