### ISSUE TITLE
Enable error

### ISSUE THREAD

**Issue by BurnBurst** [nulli0n/NexEngine-spigot#26]
Error occurred while enabling NexEngine v2.1.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at su.nexmedia.engine.NexEngine.setupNMS(NexEngine.java:94) ~[NexEngine 2.1.0.jar:?]
        at su.nexmedia.engine.NexEngine.loadCore(NexEngine.java:62) ~[NexEngine 2.1.0.jar:?]
        at su.nexmedia.engine.NexPlugin.onEnable(NexPlugin.java:66) ~[NexEngine 2.1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[paper-1.19.3.jar:git-Paper-448]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.19.3.jar:git-Paper-448]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:471) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-448]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-448]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: No enum constant su.nexmedia.engine.Version.V1_19_R2
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at su.nexmedia.engine.Version.valueOf(Version.java:6) ~[NexEngine 2.1.0.jar:?]
        at su.nexmedia.engine.Version.<clinit>(Version.java:19) ~[NexEngine 2.1.0.jar:?]
        ... 13 more

**Comment by nulli0n** [comment]
> v2.1.0 (Is it up to date?)
