### ISSUE TITLE
error pluigns

### ISSUE THREAD

**Issue by DimaSergeew** [nulli0n/NexEngine-spigot#31]
[16:32:38 ERROR]: Error occurred (in the plugin loader) while disabling NexEngine v2.2.10 build-29/03/2023 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/trait/TraitInfo
        at su.nexmedia.engine.hooks.external.citizens.CitizensHook.unregisterTraits(CitizensHook.java:85) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.unloadManagers(NexPlugin.java:242) ~[NexEngine.jar:?]
        at su.nexmedia.engine.NexPlugin.onDisable(NexPlugin.java:101) ~[NexEngine.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:151) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.disablePlugins(CraftServer.java:500) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:960) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:844) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1240) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1957]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by nulli0n** [comment]
Update Citizens or remove it.
