### ISSUE TITLE
I can't delete a reward from a crate

### ISSUE THREAD

**Issue by LaCorona** [nulli0n/NexEngine-spigot#41]
This happens when I try to delete a reward using "Q". I'm using Purpur Paper 1.17.1
``[14:17:42 ERROR]: Could not pass event InventoryClickEvent to NexEngine v2.2.11
java.lang.UnsupportedOperationException: Unsupported server version!
        at su.nexmedia.engine.utils.ItemUtil.compress(ItemUtil.java:268) ~[NexEngine.jar:?]
        at su.nexmedia.engine.api.config.JYML.setItemEncoded(JYML.java:419) ~[NexEngine.jar:?]
        at su.nightexpress.excellentcrates.crate.impl.Crate.onSave(Crate.java:211) ~[ExcellentCrates-4.4.0.jar:?]
        at su.nexmedia.engine.api.manager.ConfigHolder.save(ConfigHolder.java:20) ~[NexEngine.jar:?]
        at su.nightexpress.excellentcrates.crate.editor.CrateRewardsEditor.save(CrateRewardsEditor.java:94) ~[ExcellentCrates-4.4.0.jar:?]
        at su.nightexpress.excellentcrates.crate.editor.CrateRewardsEditor.lambda$getObjectClick$8(CrateRewardsEditor.java:135) ~[ExcellentCrates-4.4.0.jar:?]
        at su.nexmedia.engine.api.menu.impl.Menu.onClick(Menu.java:160) ~[NexEngine.jar:?]
        at su.nightexpress.excellentcrates.crate.editor.CrateRewardsEditor.onClick(CrateRewardsEditor.java:170) ~[ExcellentCrates-4.4.0.jar:?]
        at su.nexmedia.engine.api.menu.impl.MenuListener.onMenuItemClick(MenuListener.java:70) ~[NexEngine.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1428]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2891) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1421) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1560) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]``

**Comment by nulli0n** [comment]
1. Wrong repo
2. It literally says the problem: 

> Unsupported server version!
