### ISSUE TITLE
Bug NexEngine - SQL Error on player join

### ISSUE THREAD

**Issue by ArcadeProgram** [nulli0n/NexEngine-spigot#45]
My server is a Purpur 1.19.4 and run NexEngine, Excellent crates and others plugins (i don't named it because they don't use NexEngine).

Error: 
```
[20:49:36 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: dateCreated)
[20:49:36 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1179)
[20:49:36 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1190)
[20:49:36 WARN]:        at org.sqlite.core.DB.throwex(DB.java:1150)
[20:49:36 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[20:49:36 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:126)
[20:49:36 WARN]:        at org.sqlite.core.DB.prepare(DB.java:264)
[20:49:36 WARN]:        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
[20:49:36 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
[20:49:36 WARN]:        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[20:49:36 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
[20:49:36 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
[20:49:36 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:206)
[20:49:36 WARN]:        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
[20:49:36 WARN]:        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
[20:49:36 WARN]:        at NexEngine.jar//su.nexmedia.engine.api.data.sql.SQLQueries.executeStatement(SQLQueries.java:63)
[20:49:36 WARN]:        at NexEngine.jar//su.nexmedia.engine.api.data.sql.executor.UpdateQueryExecutor.execute(UpdateQueryExecutor.java:69)
[20:49:36 WARN]:        at NexEngine.jar//su.nexmedia.engine.api.data.AbstractDataHandler.update(AbstractDataHandler.java:166)
[20:49:36 WARN]:        at NexEngine.jar//su.nexmedia.engine.api.data.AbstractUserDataHandler.saveUser(AbstractUserDataHandler.java:140)
[20:49:36 WARN]:        at NexEngine.jar//su.nexmedia.engine.api.data.AbstractUser.lambda$saveData$0(AbstractUser.java:43)
[20:49:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:103)
[20:49:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[20:49:36 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:49:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:49:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:49:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

Config:
```
Plugin:
  # Command names that will be registered as main plugin commands.
  # Do not leave this empty. Split multiple names with a comma.
  Command_Aliases: nexengine
  # Sets the plugin language.
  # It will use language config from the '/lang/' sub-folder for specified language code.
  # By default uses your system's default locale.
  Language: en
  # Plugin prefix. Used in messages.
  # You can use %plugin_name_localized% placeholder for a plugin name.
  Prefix: NexEngine
  # Localized plugin name. It's used in messages and with internal placeholders.
  Name: NexEngine

Locale:
  World_Names:
    world: World
    world_nether: Nether
    world_the_end: The End
```

**Comment by nulli0n** [comment]
Reset data.db of the crates and next time do a clean install when skip a lot of upates.

**Comment by ArcadeProgram** [comment]
OK thank's
