### ISSUE TITLE
[SQLITE_ERROR] SQL error or missing database (no such column: dateCreated)

### ISSUE THREAD

**Issue by zeus1921** [nulli0n/NexEngine-spigot#46]
Hey there.

Got an error in console, and i don't know what this is, might be a column from another plugin? should i ignore it?

```
[10:27:06 WARN]: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: dateCreated)
[10:27:06 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1179)
[10:27:06 WARN]:        at org.sqlite.core.DB.newSQLException(DB.java:1190)
[10:27:06 WARN]:        at org.sqlite.core.DB.throwex(DB.java:1150)
[10:27:06 WARN]:        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
[10:27:06 WARN]:        at org.sqlite.core.NativeDB.prepare(NativeDB.java:126)
[10:27:06 WARN]:        at org.sqlite.core.DB.prepare(DB.java:264)
[10:27:06 WARN]:        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46)
[10:27:06 WARN]:        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32)
[10:27:06 WARN]:        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25)
[10:27:06 WARN]:        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34)
[10:27:06 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226)
[10:27:06 WARN]:        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:206)
[10:27:06 WARN]:        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:327)
[10:27:06 WARN]:        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
[10:27:06 WARN]:        at NexEngine.jar//su.nexmedia.engine.api.data.sql.SQLQueries.executeStatement(SQLQueries.java:63)
[10:27:06 WARN]:        at NexEngine.jar//su.nexmedia.engine.api.data.sql.executor.UpdateQueryExecutor.execute(UpdateQueryExecutor.java:69)
[10:27:06 WARN]:        at NexEngine.jar//su.nexmedia.engine.api.data.AbstractDataHandler.update(AbstractDataHandler.java:163)
[10:27:06 WARN]:        at NexEngine.jar//su.nexmedia.engine.api.data.AbstractUserDataHandler.saveUser(AbstractUserDataHandler.java:143)
[10:27:06 WARN]:        at NexEngine.jar//su.nexmedia.engine.api.data.AbstractUserManager.lambda$saveUser$3(AbstractUserManager.java:140)
[10:27:06 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:103)
[10:27:06 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[10:27:06 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:27:06 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[10:27:06 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[10:27:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by nulli0n** [comment]
Delete data.db inside plugin folder.

**Comment by zeus1921** [comment]
Same thing
