### ISSUE TITLE
Latest version doesn't work 

### ISSUE THREAD

**Issue by Miniontoby** [nulli0n/NexEngine-spigot#51]
Hi,

Latest version doesn't work on 1.19.4 (at least)

Error:
```
[19:58:46 ERROR]: Error occurred (in the plugin loader) while disabling NexEngine v2.2.4 build-29/08/2022 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "su.nexmedia.engine.hooks.HookManager.shutdown(su.nexmedia.engine.NexPlugin)" because the return value of "su.nexmedia.engine.NexPlugin.getHooks()" is null
    at su.nexmedia.engine.NexPlugin.unloadManagers(NexPlugin.java:213) ~[NexEngine.jar:?]
    at su.nexmedia.engine.NexPlugin.onDisable(NexPlugin.java:80) ~[NexEngine.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
```

For now using the previous release instead, since the latest was made 8 hours ago. That previous version works!

**Comment by nulli0n** [comment]
You should be kidding

> NexEngine v2.2.4 build-29/08/2022
