### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DimaSergeew** [nulli0n/NexEngine-spigot#7]
[18:29:34] [Server thread/ERROR]: Error occurred while disabling MoneyHunters v7.0.4 Pro (Is it up to date?)
[18:29:34] [Server thread/ERROR]: Suspected Plugins: 
[18:29:34] [Server thread/ERROR]: 	NexEngine{enabled,ver=2.2.0 build-18/06/2022,path=plugins/NexEngine.jar}
[18:29:34] [Server thread/ERROR]: Exception details below: 
java.lang.NullPointerException: Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because "su.nexmedia.engine.hooks.external.citizens.CitizensHook.traits" is null
	at su.nexmedia.engine.hooks.external.citizens.CitizensHook.unregisterTraits(CitizensHook.java:82) ~[NexEngine.jar:?]
	at su.nexmedia.engine.NexPlugin.unloadManagers(NexPlugin.java:207) ~[NexEngine.jar:?]
	at su.nexmedia.engine.NexPlugin.onDisable(NexPlugin.java:80) ~[NexEngine.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[mirai-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[mirai-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:573) ~[mirai-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:550) ~[mirai-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:495) ~[mirai-1.19.jar:git-Mirai-64a31b5]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:931) ~[mirai-1.19.jar:git-Mirai-64a31b5]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:794) ~[mirai-1.19.jar:git-Mirai-64a31b5]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1241) ~[mirai-1.19.jar:git-Mirai-64a31b5]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:304) ~[mirai-1.19.jar:git-Mirai-64a31b5]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by nulli0n** [comment]
Update Citizens.
